name: Publish to NuGet
on:
  push:
    branches: [ master ]
  release:
    types: [ created ]

jobs:
  build-publish:
    name: Build and Publish
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "5.0.x"

    - name: Pack .nupkg (Release)
      if: ${{ github.event_name == 'release' }}
      run: dotnet pack -c Release -o dist

    - name: Pack .nupkg (Pre-Release)
      if: ${{ github.event_name == 'push' }}
      run: dotnet pack -c Release -o dist --version-suffix "git-${{ github.sha }}"

    - name: Publish to NuGet
      run: dotnet nuget push dist\* --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json